In [1]:
import pandas as pd
pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', 10)

In [5]:
file = r'../data/College.csv'
college = pd.read_csv(file, index_col=0)
college

,Apps,Accept,Enroll,Top10perc,Top25perc,...,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
Private,,,,,,,,,,,
Yes,1660,1232,721,23,52,...,78,18.1,12,7041,60
Yes,2186,1924,512,16,29,...,30,12.2,16,10527,56
Yes,1428,1097,336,22,50,...,66,12.9,30,8735,54
Yes,417,349,137,60,89,...,97,7.7,37,19016,59
Yes,193,146,55,16,44,...,72,11.9,2,10922,15
...,...,...,...,...,...,...,...,...,...,...,...
No,2197,1515,543,4,26,...,60,21.0,14,4469,40
Yes,1959,1805,695,24,47,...,75,13.3,31,9189,83
Yes,2097,1915,695,34,61,...,75,14.4,20,8323,49
Yes,10705,2453,1317,95,99,...,96,5.8,49,40386,99
Yes,2989,1855,691,28,63,...,75,18.1,28,4509,99

In [4]:
college.loc['Yes']

,Apps,Accept,Enroll,Top10perc,Top25perc,...,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
Private,,,,,,,,,,,
Yes,1660,1232,721,23,52,...,78,18.1,12,7041,60
Yes,2186,1924,512,16,29,...,30,12.2,16,10527,56
Yes,1428,1097,336,22,50,...,66,12.9,30,8735,54
Yes,417,349,137,60,89,...,97,7.7,37,19016,59
Yes,193,146,55,16,44,...,72,11.9,2,10922,15
...,...,...,...,...,...,...,...,...,...,...,...
Yes,2768,2314,682,49,86,...,94,15.2,34,10774,82
Yes,1959,1805,695,24,47,...,75,13.3,31,9189,83
Yes,2097,1915,695,34,61,...,75,14.4,20,8323,49
Yes,10705,2453,1317,95,99,...,96,5.8,49,40386,99
Yes,2989,1855,691,28,63,...,75,18.1,28,4509,99

In [6]:
college.loc['Yes':'No']

KeyError: "Cannot get left slice bound for non-unique label: 'Yes'"